# Generated by Django 4.0.4 on 2022-10-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog1', '0002_contact_upsignup_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upsignup',
            name='uid',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=50),
        ),
    ]
