# Generated by Django 4.0.4 on 2022-10-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog1', '0003_remove_upsignup_uid_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upsignup',
            old_name='Phone',
            new_name='PasswordInput',
        ),
        migrations.RemoveField(
            model_name='upsignup',
            name='message',
        ),
    ]
